jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: etl
      password: Admin@123
      port: 5432
      dbname: etl
      schema: public
      threads: 4
