version: 1
default_environment: dev
project_id: d9e0d480-5c7e-4dd9-9ced-1d80cb54fb66
environments:
  - name: dev
    config:
      plugins:
        extractors:
          - name: tap-github
            select:
              - commits.url
              - commits.sha
              - commits.commit_timestamp
  - name: staging
  - name: prod
plugins:
  extractors:
    - name: tap-csv
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
      config:
        files:
          - entity: raw_customers
            path: data/customers.csv
            keys: [id]
    - name: tap-mysql
      variant: transferwise
      pip_url: pipelinewise-tap-mysql
      config:
        host: localhost
        port: 3306
        user: etl
        database: etl
        ssl: false
        engine: mysql
        default_replication_method: FULL_TABLE
      select:
        - etl-products.*
      metadata:
        "*":
          # replication-key: id
          replication-method: FULL_TABLE
    - name: tap-github
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-github.git
      config:
        start_date: 2023-02-05
        repositories:
          - yugasun/etl-starter-kit
  loaders:
    - name: target-duckdb
      variant: jwills
      pip_url: target-duckdb~=0.4
      config:
        filepath: output/my.duckdb
        default_target_schema: raw
        add_metadata_columns: true
        hard_delete: true
    - name: target-postgres
      variant: transferwise
      pip_url: pipelinewise-target-postgres
      config:
        host: localhost
        port: 5432
        user: etl
        dbname: etl # Notice: it is dbname not database
        default_target_schema: public
        ssl: false
        add_metadata_columns: true
    - name: target-jsonl
      variant: andyh1203
      pip_url: target-jsonl
  utilities:
    - name: airflow
      # refer https://hub.meltano.com/utilities/airflow/
      variant: apache
      pip_url:
        git+https://github.com/meltano/airflow-ext.git@main apache-airflow==2.3.3
        --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.3.3/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
  mappers:
    - name: transform-field
      variant: transferwise
      pip_url: pipelinewise-transform-field
      executable: transform-field
      mappings:
        - name: csv-hide-ips
          config:
            transformations:
              - field_id: ip_address
                tap_stream_name: raw_customers
                type: HASH
jobs:
  - name: github2json
    tasks:
      - tap-github target-jsonl
  - name: csv2pg
    tasks:
      - tap-csv target-postgres
  - name: csv2duckdb
    tasks:
      - tap-csv csv-hide-ips target-duckdb
  - name: mysql2json
    tasks:
      - tap-mysql target-jsonl
  - name: mysql2pg
    tasks:
      - tap-mysql target-postgres
schedules:
  - name: github2json
    interval: "@hourly"
    job: github2json
    env:
      MELTANO_PROJECT_ROOT: /Users/yugasun/Desktop/develop/etl-starter-kit/meltano
      TAP_MYSQL_PASSWORD: Admin@123
      TARGET_POSTGRES_PASSWORD: Admin@123
