version: "3.8"

services:
  # Refer to: https://hub.docker.com/_/mysql
  mysql:
    image: mysql:8.0
    container_name: etl-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_USER: etl
      MYSQL_PASSWORD: Admin@123
      MYSQL_DATABASE: etl
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  # Refer to: https://hub.docker.com/_/postgres
  postgres:
    image: postgres:12
    container_name: etl-postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: etl
    ports:
      - "5432:5432"
    volumes:
      - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  oracle:
    image: gvenzl/oracle-xe:11
    container_name: oracle
    environment:
      ORACLE_PASSWORD: Admin@123
    ports:
      - "1521:1521"

  # starrocks-fe:
  #   image: starrocks/fe-ubuntu:main
  #   hostname: starrocks-fe
  #   container_name: starrocks-fe
  #   command: /opt/starrocks/fe/bin/start_fe.sh
  #   ports:
  #     - 8030:8030
  #     - 9020:9020
  #     - 9030:9030
  #   volumes:
  #     - ./starrocks/fe.conf:/opt/starrocks/fe/conf/fe.conf
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9030"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 30

  # starrocks-be:
  #   image: starrocks/be-ubuntu:main
  #   command:
  #     - /bin/bash
  #     - -c
  #     - |
  #       sleep 15s; mysql --connect-timeout 2 -h starrocks-fe -P9030 -uroot -e "alter system add backend \"starrocks-be:9050\";"
  #       /opt/starrocks/be/bin/start_be.sh
  #   ports:
  #     - 8040:8040
  #   hostname: starrocks-be
  #   container_name: starrocks-be
  #   depends_on:
  #     - starrocks-fe
  #   volumes:
  #     - ./starrocks/be.conf:/opt/starrocks/be/conf/be.conf
